name: Frontend CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build test image
        run: docker build -t chakri1408/docker_react -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true chakri1408/docker_react npm run test
